// src/lib/components/HomeAboutMeSection.svelte
<section class="my-20 lg:my-32">
	<div class="lg:grid grid-cols-3 gap-8">
		<div>
			<h2 class="text-4xl lg:text-5xl mb-2">WHO AM I?</h2>
		</div>
		<div class="col-span-2">
			<p class="lg:text-lg">
				I'm Wint Khant Lin, a curious soul from Yangon. Half Rakhine, Half Burmese. My life is in
				touch with technology since I was a kid.
			</p>
		</div>

		<hr class="col-span-3 border-[#e2e2e2] lg:my-4 my-10" />
		<div>
			<h2 class="text-4xl lg:text-5xl mb-2">MY SKILLS</h2>
		</div>
		<div class="col-span-2">
			<p class="lg:text-lg">
				I build with HTML, CSS, JS, TS, React, Next.js, SvelteKit, Go, MongoDB, and PostgreSQL.
				Right now, I'm grinding Data Structures, Clean Code, and Design Patterns.
			</p>
		</div>
	</div>
</section>

// components/HomeAboutMeSection.vue
<template>
    <section class="my-20 lg:my-32">
        <div class="lg:grid grid-cols-3 gap-8">
            <div>
                <h2 class="text-4xl lg:text-5xl mb-2">WHO AM I?</h2>
            </div>
            <div class="col-span-2">
                <p class="lg:text-lg">
                    I'm Wint Khant Lin, a curious soul from Yangon. Half Rakhine, Half Burmese. My life is in touch with technology since I was a kid.
                </p>
            </div>

            <hr class="col-span-3 border-[#e2e2e2] lg:my-4 my-10">
            <div>
                <h2 class="text-4xl lg:text-5xl mb-2">MY SKILLS</h2>
            </div>
            <div class="col-span-2">
                <p class="lg:text-lg">I build with HTML, CSS,
                    JS, TS, React, Next.js, SvelteKit, Go, MongoDB, and PostgreSQL.
                    Right now, I'm grinding Data Structures, Clean Code, and Design Patterns.</p>
            </div>
        </div>
    </section>
</template>
