// components/FooterComponent.vue
<template>
    <footer class="min-h-[50vh] flex flex-col items-center justify-center">
        <div class="w-full">
            <div>
                <p class="text-sm text-[#818181] mb-2">CONTACT ME</p>
                <NuxtLink to="mailto:wintkhantlin@gmail.com" class="group inline-block relative">
                    <span class="text-4xl text-[#818181] hover:text-black transition-all duration-300">
                        wintkhantlin@gmail.com
                    </span>
                    <span
                        class="block absolute left-0 -bottom-2 h-[2px] bg-black w-0 group-hover:w-full transition-all duration-300 " />
                </NuxtLink>
            </div>
            <div class="flex flex-col items-end">
                <p class="text-[#818181] mb-4">SOCIAL MEDIA</p>
                <div class="space-y-0.5 flex flex-col items-end gap-2">
                    <NuxtLink to="https://github.com/wintkhantlin" target="_blank" class="text-sm text-gray-500">
                        github.com/wintkhantlin
                    </NuxtLink>
                    <NuxtLink to="https://www.linkedin.com/in/wintkhantlin/" target="_blank" class="text-sm text-gray-500 ml-4">
                        linkedin.com/in/wintkhantlin
                    </NuxtLink>
                </div>
            </div>
        </div>
    </footer>
</template>

// src/components/Footer.svelte
<footer class="py-10 bg-white text-black">
    <div class="max-w-[1200px] mx-auto px-4 grid grid-cols-2">
        <div class="space-y-2">
            <h2 class="font-bold text-4xl">Touch Me In</h2>
            <a href="mailto:wintkhantlin@gmail.com" class="text-xl hover:underline">wintkhantlin@gmail.com</a>
        </div>
        <div class="flex flex-col justify-end items-end">
            <div class="flex flex-col">
                <h2 class="text-3xl font-bold mb-2">Connect</h2>
                <a class="text-xl font-bold transition-all hover:text-[#777]" href="https://github.com/happer64bit" target="_blank">GitHub</a>
                <a class="text-xl font-bold transition-all hover:text-[#777]" href="https://facebook.com/wintkhantlin" target="_blank">Facebook</a>
                <a class="text-xl font-bold transition-all hover:text-[#777]" href="https://www.facebook.com/profile.php?id=61558294022750" target="_blank">Facebook (Work)</a>
            </div>
        </div>
        <p class="mt-4">©2025 Wint Khant Lin - All rights reserved.</p>
    </div>
</footer>
