// components/Header.tsx
import Link from "next/link";
import { ModeToggle } from "./ModeToggle";
import { Button } from "./ui/button";
import AnnouncementBar from "./AnnouncementBar";

export default function Header() {
    return (
        <>
            <AnnouncementBar />
            <nav className="supports-backdrop-blur:bg-background/60 top-0 z-50 w-full border-b bg-background/95 backdrop-blur sticky">
                <div className="container h-12 flex items-center justify-between">
                    <div className="flex items-center">
                        <Link href={"/"} className="px-4">
                            <h2 className="text-lg">HAPPER</h2>
                        </Link>
                    </div>
                    <div className="flex items-center gap-4">
                        <Link href="/blog">
                            <Button variant={"ghost"}>Blog</Button>
                        </Link>
                        <ModeToggle />
                    </div>
                </div>
            </nav>
        </>
    )
}

// src/components/Header.svelte
<script>
	import Search from "./search/Search.svelte";

</script>
<header class="sticky top-0 left-0 w-full backdrop-blur-sm z-50 border-b border-b-white/5">
    <nav class="container flex justify-between items-center py-2">
        <a href="/" class="text-lg"><b>Wint</b></a>
        <div class="flex items-center gap-6">
            <a href="/posts" class="font-semibold">Posts</a>
            <Search />
        </div>
    </nav>
</header>
