// components/HeaderComponent.vue
<template>
    <header class="py-3 sticky top-0 left-0 backdrop-blur-lg">
        <nav class="grid grid-cols-3 container z-50">
            <div class="flex items-center gap-4">
                <NuxtLink href="/posts" class="text-[#4a4a4a]">Blog</NuxtLink>
            </div>
            <div class="flex items-center justify-center">
                <NuxtLink href="/">
                    <NuxtImg src="/icons/WINT.svg" />
                </NuxtLink>
            </div>
        </nav>
    </header>
</template>

// src/components/Header.svelte
<script>
	import Search from "./search/Search.svelte";

</script>
<header class="sticky top-0 left-0 w-full backdrop-blur-sm">
    <nav class="container flex justify-between items-center py-2">
        <a href="/" class="text-lg font-bold">Wint</a>
        <div class="flex items-center gap-6">
            <a href="/posts" class="font-semibold">Posts</a>
            <Search />
        </div>
    </nav>
</header>
