// src/routes/posts/+page.svelte
<script lang="ts">
	export let data;
</script>

<div>
	<div class="max-w-[1200px] mx-auto my-10 grid gap-5 space-y-4 px-4 lg:grid-cols-3">
		{#each data.posts as post}
			<div class="transition-all hover:scale-105">
				<a href={`/posts/${post.slug}`}>
					<article class="flex min-h-60 flex-col justify-between space-y-2 bg-[#2f2f2f] p-4 rounded-2xl border-4 border-transparent hover:border-teal-500">
						<div class="space-y-2">
							<h2 class="text-2xl font-bold">{post.title}</h2>
							<div class="flex items-center gap-2">
								<div class="rounded-lg bg-white/5 px-4 py-0.5 font-bold">{post.tag}</div>
								<time>{new Date(post.publishedDate).toLocaleDateString()}</time>
							</div>
						</div>
						<p class="line-clamp-3 text-gray-300">{post.summary}</p>
					</article>
				</a>
			</div>
		{/each}
	</div>
</div>

// src/app/posts/page.tsx
import { allPosts } from "content-collections";
import Link from "next/link";

export default function PostsPage() {
    return (
        <main className="container">
            <h1 className="text-3xl font-bold mb-4">Posts</h1>
            <div className="grid gap-4">
                {allPosts.map((posts) => (
                    <Link href={"/posts/" + posts._meta.path} key={posts._meta.path} className="p-6 rounded-3xl flex flex-col justify-between min-h-[170px] bg-[#E8E8E8]">
                        <div>
                            <h3 className="text-xl">{posts.title}</h3>
                            <p className="uppercase font-sans text-sm">{posts.publishedDate.toLocaleString()}</p>
                        </div>
                        <p>{posts.summary}</p>
                        <p className="text-blue-500 flex items-center gap-2">READ ARTICLE</p>
                    </Link>
                ))}
            </div>
        </main>
    );
}
