// src/routes/posts/+page.svelte
<script lang="ts">
	export let data;
</script>

<div>
	<div class="max-w-[1200px] mx-auto my-10 grid gap-5 space-y-4 px-4 lg:grid-cols-3">
		{#each data.posts as post}
			<div class="transition-all hover:scale-105">
				<a href={`/posts/${post.slug}`}>
					<article class="flex min-h-60 flex-col justify-between space-y-2 bg-[#2f2f2f] p-4 rounded-2xl border-4 border-transparent hover:border-teal-500">
						<div class="space-y-2">
							<h2 class="text-2xl font-bold">{post.title}</h2>
							<div class="flex items-center gap-2">
								<div class="rounded-lg bg-white/5 px-4 py-0.5 font-bold">{post.tag}</div>
								<time>{new Date(post.publishedDate).toLocaleDateString()}</time>
							</div>
						</div>
						<p class="line-clamp-3 text-gray-300">{post.summary}</p>
					</article>
				</a>
			</div>
		{/each}
	</div>
</div>

// app/pages/posts/index.vue
<script setup>

const allPosts = await queryCollection('posts', {
    sort: 'publishedDate',
    order: 'desc',
}).all();

</script>

<template>
  <main class="px-4 py-6">
    <section class="divide-y divide-neutral-300">
      <NuxtLink
        :to="post.path"
        v-for="post in allPosts"
        :key="post.id"
        class="block py-4 hover:bg-neutral-50 transition"
      >
        <div class="grid lg:grid-cols-3 gap-6 py-2">
          <div>
            <h3 class="font-bold">{{ post.title }}</h3>
            <span class="text-sm text-neutral-500">{{ new Date(post.publishedDate).toLocaleDateString().replaceAll("/", "-") }}</span>
          </div>
          <div>
            <p class="text-sm text-neutral-600">{{ post.summary }}</p>
          </div>
          <div class="text-sm">
            <p class="font-semibold mb-1">Category</p>
            <p class="text-neutral-500">{{ post.categories.join(", ").toUpperCase() }}</p>
          </div>
        </div>
      </NuxtLink>
    </section>
  </main>
</template>
