// src/app/posts/[slug]/page.tsx
import { postsDictionary } from "@/lib/posts";
import { Post } from "content-collections"
import { notFound } from "next/navigation";
import 'highlight.js/styles/github.css';

export async function generateStaticParams() {
    return Object.keys(postsDictionary).map((slug) => ({
        slug,
    }));
}

async function fetchPost(slug: string): Promise<Post> {
    "use cache"

    const post = postsDictionary[slug];

    if (!post) {
        throw notFound();
    }

    return post;
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;

    const post = await fetchPost(slug);

    return {
        title: post.title,
        description: post.summary,
        openGraph: {
            title: post.title,
            description: post.summary,
            url: `https://wintkhantlin.vercel.app/posts/${slug}`,
        },
    }
}


export default async function ViewPostPage({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;
    const post = await fetchPost(slug);

    return (
        <>
            <main className="max-w-4xl prose mx-auto my-14 px-4 prose-pre:bg-transparent prose-code:border prose-code:border-gray-200 prose-code:rounded-lg prose-pre:p-0">
                <article dangerouslySetInnerHTML={{ __html: post.html }}></article>
            </main>
        </>
    )
}

// src/routes/posts/[slug]/+page.svelte
<script lang="ts">
	import type { Post } from "content-collections";

	import 'highlight.js/styles/github.min.css'

	let { data }: { data: { post: Post } } = $props();
</script>

<svelte:head>
	<title>{data.post.title}</title>
	<meta name="description" content={data.post.summary} />
	<meta name="keywords" content={data.post.keywords.join(",")} />
	<meta name="author" content="Wint Khant Lin" />
	<meta property="og:title" content={`${data.post.title} | Wint Khant Lin`} />
	<meta property="og:description" content={data.post.summary} />
</svelte:head>

<article
	class="prose prose-lg prose-pre:bg-[#fff] prose-pre:border mx-auto max-w-[800px] my-20 px-4"
>
	{@html data.post.html}
</article>
